-- Migration: create_products
-- Generated by nestgo
-- Run: nestgo migration:run

CREATE TABLE IF NOT EXISTS products (
  id          VARCHAR(36)  PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_created_at ON products (created_at DESC);

-- Rollback:
-- DROP TABLE IF EXISTS products;
